### ISSUE TITLE
Readme  enh.

### ISSUE THREAD

**Issue by PizzaProgram** [JensBorrisholt/OnlineOffline#2]
Hi,
 Please add to the readme:

 - Dependency info (Indy10)
 - What is the min. Delphi version needed?

Thanks! :-)

**Comment by JensBorrisholt** [comment]
Hi 

Thankyou for your feed back .

First of all about Indy. It is only the demo that are using Indy, and only for checking if you can see Google, or not (Online/offline). The main feature MulticastEvent  is independent of anything, but Windows. 

About Backwards Compatibility, I haven't thought much about it. with a minor change it can compile in Delphi XE 7. 

in OnlineOfflineU

Change 

```Pascal
procedure TOnlineOffline.DoNotify;
begin
  TThread.Queue(TThread.Current,
    procedure
    begin
      FStateChangedNotifiers.Invoke(FOnlineState);
    end);
end;
```
To

```pascal
procedure TOnlineOffline.DoNotify;
begin
  TThread.Queue(TThread.CurrentThread,
    procedure
    begin
      FStateChangedNotifiers.Invoke(FOnlineState);
    end);
end;
```

**Comment by PizzaProgram** [comment]
Thanks for the quick answer!
... but I think you have misunderstand me:

- I'm using Delphi 7 (No, not XE7, but the 20 years old one.)
- I've already realized this code won't run on it.
- But it took me time, so it would had helped a lot, if +1 line would be there in the `Readme.md`, and didn't had to dig into the code to find that out. 
 - Also it is not clear, what files are necessary, and which can be dropped because it's only part of the demo.

People have less and less time, and if you save 5 minutes for 1000 of us, that's a big help summarized.

Don't get me wrong, your Readme is already AWESOME! with picture and everything, I'm just trying to tell (with my poor English) how could it be even more informative.

> The main feature MulticastEvent is independent of anything, but Windows.

- This is also a very important piece of info. Please share it at Readme!

**Comment by JensBorrisholt** [comment]
MulticastEvent uses gererics and that will never run in Delphi 7. I belive with a little luck you can make i run under  Delphi 2009. But I don't have one

**Comment by PizzaProgram** [comment]
Many thanks :-) But don't worry about that.
